### PR TITLE
Adds frida script for gathering code coverage

### PR DESCRIPTION
**Pull request by yrp604**
Implements a frida script that gathers code coverage information and
saves it using drcov format.

Probably should be considered experimental, as it's the first thing I've
written with frida and Im sure I've screwed something up =p

### CODE REVIEW

**Comment by yrp604** [comment]
Of course right after submitting this I figured some other stuff to add/change. Will try to get it updated tonight.

**Comment by yrp604** [comment]
Going to create a new PR with additional features, maybe better perf.

**Comment by yrp604** [comment]
I'm bad at git.

**Comment by gaasedelen** [comment]
Frida has been picking up traction lately, so this is an awesome contribution.

I'll test and review this soon :-)

**Comment by oleavr** [comment]
This looks like an awesome use-case for Stalker, great job! 👍

Just a few notes on the Frida-specific bits:

> It is roughly two orders of magnitude slower than native execution

After some optimizations a few months back, the code generated by Stalker should only be a little bit slower. I wrote a benchmark that measured it on LZMA compression, and the ratio is currently somewhere between 1.x and 2.x slowdown. This is however after it has "warmed up" and has all the basic blocks cached, and has applied the back-patching optimizations and warmed up the inline caches. It is careful not to re-use blocks in case of self-modifying code, though, so you pay performance overhead every time it context-switches into the runtime to look up the target of a branch, followed by checking if the original code changed since it was compiled. Stalker achieves high performance by back-patching branches and updating inline caches once they're considered stable. You can configure the `Stalker.trustThreshold` property to `0` if you know that the code isn't self-modifying, and `-1` to be paranoid (never back-patch or use inline caches), and N to assume it's stable after having been executed N times.

> * It drops coverage, especially near `exit()`

The recommended way to deal with this is to hook `exit()` and friends, and send a "flush" message to the other side and wait for an acknowledgment before returning from the hook. This is implemented in frida-trace [here](https://github.com/frida/frida-python/blob/d8e2e049c53cbca2f95ac10e97a0780a8539cf33/src/frida/tracer.py#L502-L524) – feel free to lift it.

> It cannot easily detect new threads being created, thus cannot instrument them

This will require additional hooks, per OS. Each thread will be recompiling the code, though, so the warm-up cost isn't shared between all of them. (Though this won't matter if the threads happen to execute wildly different code – so this really depends on the application.)
The reason Stalker doesn't share code across the threads is so each may have different instrumentation applied through the StalkerTransformer API. (Allowing you to add/remove/replace instructions on a per-thread basis.)

> Self modifying code will confuse it

Stalker has been designed with this in mind, but it depends on how you configure `Stalker.trustThreshold`.

> function make_maps() {

Did you run into issues with the [ModuleMap](https://www.frida.re/docs/javascript-api/#modulemap) API? It supports providing a filter function if you only care about certain modules and want faster lookups.

> // It would be really nice to use 'compile' here instead of 'block',

You can safely use `'compile'`, Stalker only compiles code that it's about to execute, and it only compiles one basic block at a time. (The compilation happens lazily as it's resolving each branch for the first time – the branch at the end of each basic block is replaced by a context-switch into Stalker's runtime. (And later this may be backpatched to go directly to the generated code, depending on how you configure `Stalker.trustThreshold`).

**Comment by yrp604** [comment]
Awesome, thanks @oleavr, that is insanely helpful.

I've implemented the non-OS specific changes, and it results in a roughly 60x speedup on my little toy benchmark. My guess is the remaining latency that's being introduced is due to me streaming the events as opposed to caching and flushing. One of the potential use cases for this might be tracing applications that crash, in which case streaming events should be a bit better, albeit at the cost of speed and with the same coverage dropping near termination as `exit()`.

For the OS specific things, I'm not really able to test them on all the platforms Frida supports, so I'm inclined to leave it OS agnostic and keep it as a general limitation, as it's not too onerous and the script it still quite useful without them.

Thanks again, that's exactly the type of feedback I was hoping for.

**Comment by gaasedelen** [comment]
Wow, well we couldn't have gotten better eyes on it than that! Thanks for taking a look @oleavr :-)

**Pull request merged**
