### PR TITLE
Improve Frida coverage collection on quick exits.

### LINKED ISSUE #44: Fails to load coverage log produced by Frida
Hi, it seems like there is a bug when loading the coverage file produced by the Frida script. I know it's experimental but you may be interested in fixing it. :)

```
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/ida_integration.py", line 234, in activate
    self.action_function()
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/core.py", line 321, in interactive_load_file
    created_coverage, errors = self.director.create_coverage_from_drcov_list(drcov_list)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/director.py", line 439, in create_coverage_from_drcov_list
    if coverage.suspicious:
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/lighthouse/coverage.py", line 210, in suspicious
    percent = (bad/float(total))*100
ZeroDivisionError: float division by zero
```

The coverage data produced by PIN loads fine on the same executable. It is a simple C test program compiled to a Mach-O executable.

```c
#include <stdio.h>
#include <string.h>

void main(int argc, char** argv) {

	char foo[20];
	gets(foo);

	if (strcmp(foo, "a") == 0) {
		printf("foo\n");
	} else {
		printf("bar\n");
	}
}
```

I've attached the failing `frida-cov.log` file.

[frida-cov.log](https://github.com/gaasedelen/lighthouse/files/2476238/frida-cov.log)

### PR DESCRIPTION
**Pull request by Ayrx**
This change makes frida-drcov.py _a lot_ more reliable when it comes to collecting coverage information, especially for binaries that exit really quickly.

The main insight here is that Stalker's `onReceive()` only triggers every 250ms by default (controllable by setting `Stalker.queueDrainInterval`). Currently, for binaries that exit before 250ms, you will essentially not collect any coverage data. For other binaries, the basic blocks that gets triggered in the last 250ms or so before an exit will not be collected.

In this change, we add a `dispose()` function to `rpc.exports`. This is a new API that got introduced in Frida 10.8 that gets called before a binary exits. This function sends a RPC message to our Python script, which then waits for 300ms before replying. This gives Stalker enough time to trigger a last queue drain before the program exits. This _should_ have the effect of not dropping any coverage near a program's exit.

Fixes #44.

cc @yrp604

### CODE REVIEW

**Comment by gaasedelen** [comment]
LGTM 👍 

Thanks for the contribution! :-)

**Comment by Ayrx** [comment]
@yrp604 I'm not quite sure yet. It's possible the Frida developers just did not think of Stalker when implementing the flush. I'll ping them and ask. :)

**Comment by Ayrx** [comment]
Frida dev's have confirmed that it's missing functionality. I'm tracking the issue at frida/frida-core#218.

**Comment by yrp604** [comment]
Awesome, great work! If the frida patch lands I'd like to roll this PR back -- it's clearly good code, it would just duplicate core frida behavior at that point and I think there's benefit to keeping the existing cov tool as lean-and-mean as possible. The impression from the frida community is that most people stay up to date and there wouldn't be a lot to be gained by supporting versions 10.8 <= x < fixed version. Thoughts?

**Comment by Ayrx** [comment]
Yes, that would be ideal. Frida users are definitely encouraged to use the latest and greatest.

**Comment by gaasedelen** [comment]
Cool! Thanks for the follow-up discussion, guys. 

I agree that most Frida users are likely up-to-date simply because of Pip. That said, I've merged the changes in for the meantime. We can revert them when we see a proper fix propagate through a Frida release.

**Pull request merged**
