### PR TITLE
Minor changes, to compile on Windows with VS2017

### PR DESCRIPTION
**Pull request by Jakob6174**
Also suppressed an 'LNK4281' warning introduced in later versions

### CODE REVIEW

**Comment by yrp604** [comment]
@agustingianni

**Comment by gaasedelen** [comment]
Thanks!

I trust that these work, but will double check for he v0.9 release :-)

**Comment by gaasedelen** [comment]
Sorry, I messed up and forgot to change your merge over to the develop branch. Master is reserved for releases.

Moving it over now...

**Comment by gaasedelen** [comment]
This has been cherry-pick'd over to develop. Thanks!

**Pull request merged**
